version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: movie-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/moviedb
    depends_on:
      - mongo
    command: flask run --host=0.0.0.0

  frontend:
    build: ./frontend
    container_name: movie-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:5000

volumes:
  mongo-data: